//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 屏幕截图2005.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("屏幕截图2005.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap B_Nomal {
            get {
                object obj = ResourceManager.GetObject("B_Nomal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap B_Selected {
            get {
                object obj = ResourceManager.GetObject("B_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorButton {
            get {
                object obj = ResourceManager.GetObject("colorButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorbutton1 {
            get {
                object obj = ResourceManager.GetObject("colorbutton1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorPalette {
            get {
                object obj = ResourceManager.GetObject("colorPalette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CT_Normal {
            get {
                object obj = ResourceManager.GetObject("CT_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CT_Selected {
            get {
                object obj = ResourceManager.GetObject("CT_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Cursor_Color {
            get {
                object obj = ResourceManager.GetObject("Cursor_Color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cursor_Cross {
            get {
                object obj = ResourceManager.GetObject("Cursor_Cross", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cursor_Default {
            get {
                object obj = ResourceManager.GetObject("Cursor_Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cursor_Red {
            get {
                object obj = ResourceManager.GetObject("Cursor_Red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Cursor_Text {
            get {
                object obj = ResourceManager.GetObject("Cursor_Text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon cutImage {
            get {
                object obj = ResourceManager.GetObject("cutImage", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CW_Normal {
            get {
                object obj = ResourceManager.GetObject("CW_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CW_Selected {
            get {
                object obj = ResourceManager.GetObject("CW_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fontSytle {
            get {
                object obj = ResourceManager.GetObject("fontSytle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Gif_Components {
            get {
                object obj = ResourceManager.GetObject("Gif_Components", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap I_Normal {
            get {
                object obj = ResourceManager.GetObject("I_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap I_Selected {
            get {
                object obj = ResourceManager.GetObject("I_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Arrowhead {
            get {
                object obj = ResourceManager.GetObject("Icon_Arrowhead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Circular {
            get {
                object obj = ResourceManager.GetObject("Icon_Circular", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Ellipse {
            get {
                object obj = ResourceManager.GetObject("Icon_Ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_Rectangle {
            get {
                object obj = ResourceManager.GetObject("Icon_Rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_ToolTips {
            get {
                object obj = ResourceManager.GetObject("Icon_ToolTips", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lock {
            get {
                object obj = ResourceManager.GetObject("Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap penColor {
            get {
                object obj = ResourceManager.GetObject("penColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap penStyle {
            get {
                object obj = ResourceManager.GetObject("penStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SanJiaoKuai {
            get {
                object obj = ResourceManager.GetObject("SanJiaoKuai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon setup_16 {
            get {
                object obj = ResourceManager.GetObject("setup_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon setup_32 {
            get {
                object obj = ResourceManager.GetObject("setup_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon setup_48 {
            get {
                object obj = ResourceManager.GetObject("setup_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolBox_Normal {
            get {
                object obj = ResourceManager.GetObject("ToolBox_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolBox_Selected {
            get {
                object obj = ResourceManager.GetObject("ToolBox_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tools {
            get {
                object obj = ResourceManager.GetObject("tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ToolsBox {
            get {
                object obj = ResourceManager.GetObject("ToolsBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap U_Normal {
            get {
                object obj = ResourceManager.GetObject("U_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap U_Selected {
            get {
                object obj = ResourceManager.GetObject("U_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap X {
            get {
                object obj = ResourceManager.GetObject("X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
